spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: blabla
    password: blabla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true